### ISSUE TITLE
Generate status JSON file(s) with stable URL

### ISSUE THREAD

**Issue by rail** [mozilla-releng/releasewarrior-2.0#15]
I want to use the JSON files we generate without cloning the repo (read in browser). Github provides APIs for listing the repos, but it has rate limits (60 rph for anonymous requests). We can generate status files (I can think at least about inflight.json) with every update to the data. This way I can point my client to this file and get a list of releases and pointers to the actual JSON files.

**Comment by srfraser** [comment]
To make sure I've understood - this would essentially be one big json file that had the contents of all the inflight json files in it. For example:

    {
        "firefox": {
            { ... contents of firefox-release-57.0.2.json },
            { ... contents of firefox-beta-foo.json },
        }
    }

**Comment by rail** [comment]
I think I don't need this feature anymore. Let's kill it!
