### ISSUE TITLE
Broken Bugzilla links

### ISSUE THREAD

**Issue by nthomas-mozilla** [mozilla-releng/releasewarrior-2.0#20]
eg I got http://bugzilla/1420536 in https://github.com/mozilla-releng/releasewarrior-data/blob/master/inflight/thunderbird/thunderbird-beta-58.0b1.md

Just a s,http://bugzilla,https://bugzil.la, in templates/markdown/generic.md.tmpl ?

**Comment by nthomas-mozilla** [comment]
* typo 'Descripiton' in the table header
* 'Release unblocked' and 'Future threat' are opposite sense, how about 'Release blocked' and 'Future threat' ?

**Comment by srfraser** [comment]
Links fixed.

I'm unsure about the 'Release blocked' change - I agree that 'release blocked' sounds better, I'm just unsure of what might bite us with changing the value passed to the template later.

**Comment by nthomas-mozilla** [comment]
I see that state is stored as `resolved` in the json, and if we were to s/Release Unblocked/Resolved/ for the label I'd be happier. Your bikeshed may vary, and I can train my brain to cope with how it is now. Please resolve this issue whichever way you think best.

**Comment by nthomas-mozilla** [comment]
And of course, thank you for actually landing these fixes!

**Comment by lundjordan** [comment]
I think this is fixed.
