### ISSUE TITLE
update fennec docs to use flavour: ship_fennec

### ISSUE THREAD

**Issue by lundjordan** [mozilla-releng/releasewarrior-2.0#50]
jlund> hm
18:20:40 [task 2018-01-24T02:19:29.600092Z]     promotion_config = RELEASE_PROMOTION_CONFIG[release_promotion_flavor]
18:20:40 [task 2018-01-24T02:19:29.600152Z] KeyError: u'publish_fennec'
18:20:42 https://public-artifacts.taskcluster.net/GjsWwxGWS9mNcgYs4CSsYQ/0/public/logs/live_backing.log
18:22:58 aki: ^ re: https://github.com/mozilla-releng/releasewarrior-2.0/wiki/Push-to-Google-Play#creating-the-release-promotion-graph
18:23:12 trying to create the publish graph for 59.0b3 fennec
18:23:20 
<•aki> should be push i think
18:23:21 
<•jlund> desktop beta and devedition worked
18:23:24 
<•aki> or ship
18:23:54 
<•jlund> https://dxr.mozilla.org/mozilla-central/source/taskcluster/taskgraph/actions/release_promotion.py#27
18:23:55 ah
18:24:02 
<•aki> ship_fennec https://hg.mozilla.org/releases/mozilla-beta/file/tip/taskcluster/taskgraph/actions/release_promotion.py#l27
18:24:03 yeah
18:24:05 
<mozdef> NOTICE: access SSH login from 10.26.48.19 on buildbot-master85.bb.releng.scl3.mozilla.com as user jlund
18:24:10 
<•aki> sorry, did that get renamed without a doc update?
18:24:13 
<•jlund> ha
18:24:24 interesting channel I decided to ping in
18:25:12 looks like it: https://hg.mozilla.org/mozilla-central/diff/77de103de179/taskcluster/taskgraph/actions/release_promotion.py#l1.48
18:25:19 I'll create a rw issue

**Comment by escapewindow** [comment]
https://github.com/mozilla-releng/releasewarrior-2.0/wiki/Push-to-Google-Play/_compare/f00c8ff893709ca3f9ef28fbb14bacbe00237eeb...9c115b8ffd9b625fb455439eaa7d76b846b44ad9

**Comment by escapewindow** [comment]
hm, that may cause issues for m-r. should we fork that page?

**Comment by lundjordan** [comment]
This was patched for beta templates. I think release templates will be pointed to old docs in: https://github.com/mozilla-releng/releasewarrior-2.0/pull/57

Once we have that, we can close this issue

**Comment by escapewindow** [comment]
Fixed release earlier this cycle.
