### ISSUE TITLE
add ability to update graphids outside of manual json update + sync

### ISSUE THREAD

**Issue by lundjordan** [mozilla-releng/releasewarrior-2.0#52]

**Comment by escapewindow** [comment]
Related: https://trello.com/c/z1N9tif8/291-improve-how-we-find-the-action-taskids checkbox 2 -

```
add phases to releasewarrior. we already get the graph IDs and populate the template; having the phases there would allow releaseduty to look at the markdown or json and go from there
```

This might look like `--graph-id promote:abcd1234` which would allow for a label for each graph id.

**Comment by MihaiTabara** [comment]
Neat to also be able to add a graphid on the fly. For shipping graphs which are generated after QE signoff, there's no way of adding them into the warrior-date other than manual json update + sync.
