### ISSUE TITLE
--gtb-date for track should support yearless entry

### ISSUE THREAD

**Issue by Callek** [mozilla-releng/releasewarrior-2.0#7]
When doing a ```release track --gtb-date 11-27``` I would have expected it to resolve to todays year and output as ```2017-11-27``` rather than bare ```11-27``` We should make this easy on humans.

Additionally I'd expect it to default to "future" thus if I entered ```1-13``` (or 01-13) it would default to ```2018-01-13```.

**Comment by lundjordan** [comment]
absolutely. I'd love to have more flexible date inputs
